{{- range $k, $v := .Values.configmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$.Values.env}}-{{$.Values.project}}-{{ $v.name }}-cm
  namespace: {{ $.Release.Namespace }}
data:
  {{ $v | toYaml | indent 2 | trim }}
{{- end }}